{% set version = "3.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggsci
  version: {{ version|replace("-", "_") }}

source:
  fn: ggsci_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggsci_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggsci/ggsci_{{ version }}.tar.gz
  sha256: 5934b232e6843cf499d3db9b6f90c4239bbc1643df625f50ec45c13add5fbea9

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ggplot2 >=2.0.0
    - r-scales
  run:
    - r-base
    - r-ggplot2 >=2.0.0
    - r-scales

test:
  commands:
    - $R -e "library('ggsci')"           # [not win]
    - "\"%R%\" -e \"library('ggsci')\""  # [win]

about:
  home: https://nanx.me/ggsci/, https://github.com/road2stat/ggsci
  license: GPL-3
  summary: A collection of 'ggplot2' color palettes inspired by plots in scientific journals, data visualization libraries, science fiction movies, and TV shows.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
